<a href="https://colab.research.google.com/github/jitendra2425/DEEPLEARNING-EXP/blob/main/manipulating_tensors_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

import tensorflow as tf
try:
 tf.executing_eagerly()
 print("TF imported with eager execution!")
except ValueError:
 print("TF already imported with eager execution!")
even = tf.constant([2, 4, 6, 8, 10, 12], dtype=tf.int32)
print("even:", even)
ones = tf.ones([6], dtype=tf.int32)
print("ones:", ones)
just_beyond_primes = tf.add(even, ones)
print("just_beyond_primes:", just_beyond_primes)
twos = tf.constant([2, 2, 2, 2, 2, 2], dtype=tf.int32)
primes_doubled = even * twos
print("primes_doubled:", primes_doubled)
some_matrix = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.int32)
print(some_matrix)
print("\nvalue of some_matrix is:\n", some_matrix.numpy())

TF imported with eager execution!
even: tf.Tensor([ 2  4  6  8 10 12], shape=(6,), dtype=int32)
ones: tf.Tensor([1 1 1 1 1 1], shape=(6,), dtype=int32)
just_beyond_primes: tf.Tensor([ 3  5  7  9 11 13], shape=(6,), dtype=int32)
primes_doubled: tf.Tensor([ 4  8 12 16 20 24], shape=(6,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

value of some_matrix is:
 [[1 2 3]
 [4 5 6]]


In [3]:

import tensorflow as tf
try:
 tf.executing_eagerly()
 print("TF imported with eager execution!")
except ValueError:
 print("TF already imported with eager execution!")
even = tf.constant([2, 4, 6, 8, 10, 12], dtype=tf.int32)
print("even:", even)
ones = tf.ones([6], dtype=tf.int32)
print("ones:", ones)
just_beyond_primes = tf.add(even, ones)
print("just_beyond_primes:", just_beyond_primes)
twos = tf.constant([2, 2, 2, 2, 2, 2], dtype=tf.int32)
primes_doubled = even * twos
print("primes_doubled:", primes_doubled)
some_matrix = tf.constant([[1, 2, 3], [4, 5, 6],[7,8,9]], dtype=tf.int32)
print(some_matrix)
print("\nvalue of some_matrix is:\n", some_matrix.numpy())

TF imported with eager execution!
even: tf.Tensor([ 2  4  6  8 10 12], shape=(6,), dtype=int32)
ones: tf.Tensor([1 1 1 1 1 1], shape=(6,), dtype=int32)
just_beyond_primes: tf.Tensor([ 3  5  7  9 11 13], shape=(6,), dtype=int32)
primes_doubled: tf.Tensor([ 4  8 12 16 20 24], shape=(6,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)

value of some_matrix is:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:

import tensorflow as tf
try:
 tf.executing_eagerly()
 print("TF imported with eager execution!")
except ValueError:
 print("TF already imported with eager execution!")
even = tf.constant([2, 4, 6, 8, 10, 12], dtype=tf.int32)
print("even:", even)
ones = tf.ones([6], dtype=tf.int32)
print("ones:", ones)
just_beyond_primes = tf.add(even, twos)
print("just_beyond_primes:", just_beyond_primes)
twos = tf.constant([2, 2, 2, 2, 2, 2], dtype=tf.int32)
primes_doubled = even * twos
print("primes_doubled:", primes_doubled)
some_matrix = tf.constant([[1, 2, 1], [3, 4, 1],[5,6, 1],[7,8,1],[9,10,1]], dtype=tf.int32)
print(some_matrix)
print("\nvalue of some_matrix is:\n", some_matrix.numpy())

TF imported with eager execution!
even: tf.Tensor([ 2  4  6  8 10 12], shape=(6,), dtype=int32)
ones: tf.Tensor([1 1 1 1 1 1], shape=(6,), dtype=int32)
just_beyond_primes: tf.Tensor([ 4  6  8 10 12 14], shape=(6,), dtype=int32)
primes_doubled: tf.Tensor([ 4  8 12 16 20 24], shape=(6,), dtype=int32)
tf.Tensor(
[[ 1  2  1]
 [ 3  4  1]
 [ 5  6  1]
 [ 7  8  1]
 [ 9 10  1]], shape=(5, 3), dtype=int32)

value of some_matrix is:
 [[ 1  2  1]
 [ 3  4  1]
 [ 5  6  1]
 [ 7  8  1]
 [ 9 10  1]]
